apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-data-service
  name: spring-data-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: spring-data-service
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}