apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-service
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - endpoints
      - namespaces
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway-service
subjects:
  - kind: ServiceAccount
    name: default