apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: gateway-service
  labels:
    app: gateway-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway-service
  type: NodePort