apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-service
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - env:
            - name: KUBERNETES_TRUST_CERTIFICATES
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: csplinter/gateway-service:1.0.0-SNAPSHOT
          imagePullPolicy: Never
          name: gateway-service
          ports:
            - name: http
              containerPort: 8080
            - name: actuator
              containerPort: 8085
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: actuator